#Requires AutoHotkey v2.0

; This AutoHotkey script runs tests winkey.exe by sending keyboard press messages to the kernel.
; It then checks the differences between the winkey log file and the expected logs.

; Path to the log file generated by winkey.exe
logFile := "../ks.log"
; Path to the file containing the expected logs
answerFile := "./expected.txt"


; ---------------------------------------------
; Simulate key presses
; ---------------------------------------------

; Wait 2 seconds to focus Winkey logger window
Sleep 2000

; -----------------------------
; Normal sentence
; -----------------------------
Send("The quick brown fox jumps over the lazy dog.")
Sleep 100

; -----------------------------
; Numbers and Shifted symbols
; -----------------------------
numbersAndSymbols := "09!@|-_\$%&*"
Loop 13
{
    Send(SubStr(numbersAndSymbols, A_Index, 1)) ; Shifted symbol
    Sleep 50
}

; -----------------------------
; Ctrl combo (representative)
; -----------------------------
Send("^s")  ; Ctrl+S
Sleep 50

; -----------------------------
; Shift combos (representative letters)
; -----------------------------
Send("+a")  ; Shift+A
Sleep 50
Send("+b")  ; Shift+B
Sleep 50

; -----------------------------
; Left Alt combos (representative)
; -----------------------------
Send("!f")  ; Alt+F
Sleep 50
Send("!e")  ; Alt+E
Sleep 50

; -----------------------------
; AltGr / RightAlt combos (representative)
; -----------------------------
Send("{RAlt down}q{RAlt up}") ; AltGr+Q (DE layout → @)
Sleep 50
Send("{RAlt down}e{RAlt up}") ; AltGr+E (FR layout → €)
Sleep 50

; -----------------------------
; Function key F3 only
; -----------------------------
Send("{F7}")
Sleep 50

; -----------------------------
; Common special keys
; -----------------------------
Send("{Tab}")
Sleep 50
Send("{Backspace}")
Sleep 50
Send("{Esc}")
Sleep 50
Send("{Space}")
Sleep 50
Send("{Up}")
Sleep 50
Send("{Down}")
Sleep 50
Send("{Left}")
Sleep 50
Send("{Right}")
Sleep 50
Send("{Home}")
Sleep 50
Send("{End}")
Sleep 50
Send("{Insert}")
Sleep 50
Send("{Enter}")
Sleep 50

MsgBox("Test script finished sending keys to Winkey logger!")


; ------------------------------------------------------------


; ---------------------------------------------
; Check the differences between the logs
; ---------------------------------------------

; Read files
expected := FileRead(answerFile)
content := FileRead(logFile)

; Remove newlines
expected := StrReplace(expected, "`r")
expected := StrReplace(expected, "`n")
content := StrReplace(content, "`r")
content := StrReplace(content, "`n")

; Compare lengths
minLen := (StrLen(content) < StrLen(expected)) ? StrLen(content) : StrLen(expected)
diffPositions := []

; 
Loop minLen
{
    c1 := Ord(SubStr(content, A_Index, 1))
    c2 := Ord(SubStr(expected, A_Index, 1))
    if c1 != c2
    {
        ; The MsgBox function in AutoHotkey v2 displays a popup window
        MsgBox("Diff at position " A_Index ": log=" c1 ", expected=" c2)
        ExitApp  ; immediately stops the script
    }
}


; ---------------------------------------------
; Show success message when logs match perfectly
; ---------------------------------------------

; Syntax: MsgBox(Text, Title, Options)
;  - Text:   The message to display.
;  - Title:  The window title.
;  - Options: Define the icon or buttons. 
;             "Iconi" = information icon, "Iconx" = error icon, etc.

MsgBox(
    "Log matches expected string perfectly!",
    "Test Result",
    "Iconi"
)
